name: Build & Ship

on:
  push:
    branches:
      - main # 在 main 分支发生 push 事件时触发工作流

jobs:
  desktop-build:
    runs-on: windows-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟

    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4

      # Step 2: 下载并配置 JBR (JetBrains Runtime)（如果缓存未命中）
      - name: Download and Extract JBR
        run: |
          mkdir -p C:\jbr
          curl -L -o C:\jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-windows-x64-b1312.2.tar.gz

      # Step 3: 配置 JAVA_HOME 环境变量
      - name: Configure JAVA_HOME
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: C:\jbr.tar.gz
          java-version: '17.0.11'
          architecture: x64
          cache: 'gradle'
          cache-dependency-path: | # optional
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties
        
      # Step 4: 构建 EXE
      - name: Build exe app
        run: |
          .\gradlew -Dorg.gradle.java.home=C:\jbr
          .\gradlew packageUberJarForCurrentOS
          .\gradlew createDistributable
          .\gradlew packageExe

      # Step 5: 保存构建产物
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distributable
          if-no-files-found: ignore
          path: composeApp/build
