name: Build & Ship

on:
  push:
    branches:
      - main # 在 main 分支发生 push 事件时触发工作流

jobs:
  desktop-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟

    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4

      # Step 1: 恢复 JBR 缓存
      - name: Restore JBR Cache
        uses: actions/cache@v3
        with:
          path: /home/runner/jbr # 缓存路径
          key: jbr # 缓存的唯一标识
          restore-keys: jbr-r

      # Step 2: 下载并配置 JBR (JetBrains Runtime)（如果缓存未命中）
      - name: Download and Extract JBR
        if: ${{ steps.cache-jdk.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p /home/runner/jbr
          curl -L -o /home/runner/jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-linux-x64-b1312.2.tar.gz
          tar -xzf /home/runner/jbr.tar.gz -C /home/runner/jbr --strip-components=1
        env:
          JBR_HOME: /home/runner/jbr
      # Step 3: 配置 JAVA_HOME 环境变量
      - name: Configure JAVA_HOME
        run: echo "JAVA_HOME=/home/runner/jbr" >> $GITHUB_ENV
        
      # Step 4: 验证 JBR 配置是否成功
      - name: Verify JBR
        run: $JAVA_HOME/bin/java -version
          
      # Step 3：打印
      - name: Print
        run: |
          echo "jbr目录下 ：  $(ls -a /home/runner/jbr)"
          echo "当前目录：$(pwd)"
          
      # Step 4: 配置 Java 环境变量
      - name: Configure Java Environment Variables
        run: |
          echo "JAVA_HOME=/home/runner/jbr" >> $GITHUB_ENV
          echo "PATH=/home/runner/jbr/bin:$PATH" >> $GITHUB_ENV

      # Step 5: 构建EXE
      - name: Build exe app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          run: |
            ./gradlew packageUberJarForCurrentOS
            ./gradlew createDistributable
            ./gradlew packageExe

      # Step 6：打印
      - name: Print
        run: |
          echo "文件路径遍历1：$(ls -R build)"
          
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributable-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            build
